/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package galadriel;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author Camil
 */
public class AvatarFemininoView extends javax.swing.JFrame {
    
   private DefaultListModel<AvatarFeminino> listaModel;
   public AvatarFemininoView() {
       listaModel = new DefaultListModel<AvatarFeminino>();
       initComponents();
   }

    /**
     * Creates new form AvatarFemininoView
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeAvatarjTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idadeAvatarjTextField2 = new javax.swing.JTextField();
        alturaAvatarjTextField3 = new javax.swing.JTextField();
        pesoAvatarjTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        insereBancojButton1 = new javax.swing.JButton();
        carregarBancojButton2 = new javax.swing.JButton();
        limparListajButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AvatarFemininoViewjList1 = new javax.swing.JList<AvatarFeminino>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        nomeAvatarjTextField1.setText("Xena de Amphipolis");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("        Gerador de Avatares Femininos");

        jLabel3.setText("Idade:");

        jLabel4.setText("Altura:");

        jLabel5.setText("Peso:");

        idadeAvatarjTextField2.setText("18");

        alturaAvatarjTextField3.setText("177");
        alturaAvatarjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaAvatarjTextField3ActionPerformed(evt);
            }
        });

        pesoAvatarjTextField4.setText("64");

        jLabel6.setText("KG");

        jLabel7.setText("CM");

        insereBancojButton1.setText("INSERIR NO BANCO");

        carregarBancojButton2.setText("CARREGAR DO BANCO");

        limparListajButton3.setText("LIMPAR");

        jLabel9.setText("Anos");

        AvatarFemininoViewjList1.setModel(listaModel);
        jScrollPane2.setViewportView(AvatarFemininoViewjList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carregarBancojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparListajButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pesoAvatarjTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                    .addComponent(idadeAvatarjTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alturaAvatarjTextField3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)))
                            .addComponent(nomeAvatarjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(insereBancojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomeAvatarjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idadeAvatarjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(alturaAvatarjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(pesoAvatarjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insereBancojButton1)
                        .addGap(12, 12, 12)
                        .addComponent(carregarBancojButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparListajButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alturaAvatarjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaAvatarjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaAvatarjTextField3ActionPerformed

    public AvatarFeminino obterAvatarFemininoDigitado(){
        String nome = nomeAvatarjTextField1.getText();
        int idade = Integer.parseInt(idadeAvatarjTextField2.getText());
        double altura = Double.parseDouble(alturaAvatarjTextField3.getText());
        double peso = Double.parseDouble(pesoAvatarjTextField4.getText());
        AvatarFeminino af = new AvatarFeminino(nome, idade, altura, peso);
        return af;
    }
    
    public void inserelista(AvatarFeminino af){
        listaModel.addElement(af);
    }
    public void limparLista(){
        listaModel.clear();
    }
    public void addInserirBancoListener(ActionListener al){
        insereBancojButton1.addActionListener(al);
    }
    public void addCarregarBancoListener(ActionListener al){
        carregarBancojButton2.addActionListener(al);
    }
    public void addLimparListaListener(ActionListener al){
        limparListajButton3.addActionListener(al);
    }
    
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<AvatarFeminino> AvatarFemininoViewjList1;
    private javax.swing.JTextField alturaAvatarjTextField3;
    private javax.swing.JButton carregarBancojButton2;
    private javax.swing.JTextField idadeAvatarjTextField2;
    private javax.swing.JButton insereBancojButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limparListajButton3;
    public javax.swing.JTextField nomeAvatarjTextField1;
    private javax.swing.JTextField pesoAvatarjTextField4;
    // End of variables declaration//GEN-END:variables
}
